# Generated by Django 4.1.4 on 2022-12-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Join_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=1000)),
                ('gender', models.CharField(default='', max_length=1000)),
                ('email', models.CharField(default='', max_length=1000)),
                ('mobile_number', models.CharField(default='', max_length=1000)),
                ('qualification', models.CharField(default='', max_length=1000)),
                ('experience', models.CharField(default='', max_length=1000)),
                ('location', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
